os: windows
language: cpp
env: PATH=/c/Python39:/c/Python39/Scripts:$PATH
before_install:
  - choco install python
  - python -m pip install --upgrade pip
  - pip install --user cpp-coveralls
install:
  - choco install visualstudio2019community
  - choco install visualstudio2019-workload-nativedesktop
  - ./setup_libs.bat -msvc 64
script:
  - ./build.bat -debug -msvc 64
afrer_success:
  - coveralls --exclude libs --gcov-options '\-lp'
