remote_theme: pmarsceill/just-the-docs

title: win-vind
description: Simple Vim Key Binder for Windows
logo: /imgs/win-vind-icon_wt.png

search_enabled: true

aux_links:
    "Download 32bit":
        - "https://github.com/pit-ray/win-vind/releases/download/v3.2.2/setup_win-vind_3.2.2_32bit.exe.zip"
    
    "Download 64bit":
        - "https://github.com/pit-ray/win-vind/releases/download/v3.2.2/setup_win-vind_3.2.2_64bit.exe.zip"
        
    "GitHub":
        - "//github.com/pit-ray/win-vind"

aux_links_new_tab: false

heading_anchors: true

go_tracking: UA-121829043-2

color_scheme: mono
