version: 1.0.{build}
max_jobs: 12
clone_depth: 1
install:
- cmd: cmd /c "call setup_libs.bat -msvc 64"
before_build:
- cmd: build.bat -debug -msvc 64
build:
  project: debug/win-vind.sln
  parallel: true
  verbosity: minimal
