name: auto release

on:
  push:
    tags:
      - v*.*.*

jobs:
  x64-and-x86:
    runs-on: windows-latest

    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2

    - name: Install NSIS
      run: |
        Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop bucket add extras
        scoop install nsis

    - name: Get the version
      id: version
      run: |
        $TAG=$($(echo ${{github.ref}}).Replace('refs/tags/v', ''))
        echo "::set-output name=tag::$TAG"

    - name: Setup x64 MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Cache x64 libraries
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/libs
        key: x64-libs-cache-210801

    - name: Setup x64 libraries
      run: ./tools/setup_libs.bat -msvc 64
 
    - name: Build x64 assets
      run: ./tools/create_assets.bat ${{steps.version.outputs.tag}} -msvc 64


    - name: Setup x86 MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Cache x86 libraries
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/libs
        key: x86-libs-cache-210801

    - name: Setup x86 libraries
      run: ./tools/setup_libs.bat -msvc 32

    - name: Build x86 assets
      run: ./tools/create_assets.bat ${{steps.version.outputs.tag}} -msvc 32


    - name: Create release and submit assets
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          bin_64/*64bit.exe.zip
          bin_64/*64bit.zip
          bin_32/*32bit.exe.zip
          bin_32/*32bit.zip
