name: cov-build

on:
  schedule:
    - cron: '0 18 * * 4'

  push:
    tags:
      - v*.*.*
      - coverity*

  pull_request:
    branches:
      - master
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'src/**'
      - '.github/**'
      - 'tests/**'
      - 'tools/**'

env:
  TOKEN: ${{secrets.COVERITY_TOKEN}}
  EMAIL: ${{secrets.COVERITY_EMAIL}}

jobs:
  x64:
    runs-on: windows-latest

    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2

    - name: Setup Environment
      run: |
        choco install -y unzip
        choco install -y mingw --version=10.3.0

    - name: Export Path
      run: |
        echo "before-env: GITHUB_PATH"
        cat $env:GITHUB_PATH
        @("C:\ProgramData\chocolatey\bin") + (Get-Content $env:GITHUB_PATH) | Set-Content $env:GITHUB_PATH
        echo "after-env: GITHUB_PATH"
        cat $env:GITHUB_PATH
        refreshenv

    - name: Cache libraries
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/libs
        key: x64-libs-cache-coverity-220126

    - name: Install libraries
      run: "tools/setup_libs.bat -mingw 64"

    - name: Cache Coverity scan tools
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/cov_tools
        key: x64-coverity-cache-210829-4

    - name: Install Coverity scan tools
      run: "tools/install_coverity_tools.bat $TOKEN"

    - name: Configure CMake
      run: |
        cov_tools/bin/cov-configure --config build/covtest/cov.xml --comptype g++ --compiler g++ --template
        cmake -B build -DCMAKE_BUILD_TYPE=Debug -G "MinGW Makefiles" -DBIT_TYPE=64 -DCCACHE_ENABLE=OFF .

    - name: Build with Coverity
      run: |
        cov_tools/bin/cov-build --config build/covtest/cov.xml --dir build/cov-int cmake --build build
        cd build
        tail cov-int/build-log.txt
        tar -czvf cov-int.tgz cov-int
        cd ..

    - name: Submit tarball to Coverity
      run: curl --form token=$TOKEN --form email=$EMAIL --form file=@build/cov-int.tgz --form version="${{github.sha}}" --form description="Automatic submission with GitHub Actions" https://scan.coverity.com/builds?project=pit-ray%2Fwin-vind
      shell: cmd
