name: cov-build

on:
  schedule:
    - cron: '0 18 * * 4'

  push:
    tags:
      - v*.*.*
      - coverity*

  pull_request:
    branches:
      - master
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'src/**'
      - '.github/**'
      - 'tests/**'
      - 'tools/**'

env:
  TOKEN: ${{secrets.COVERITY_TOKEN}}
  EMAIL: ${{secrets.COVERITY_EMAIL}}
  OUTDIR: ${{github.workspace}}/build

jobs:
  x64:
    runs-on: windows-latest

    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install tools
      run: |
        choco install -y unzip

    - name: Cache libraries
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/libs
        key: x64-libs-cache-coverity-220126

    - name: Install libraries
      run: "tools/setup_libs.bat -msvc 64"

    - name: Cache Coverity scan tools
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/cov_tools
        key: x64-coverity-cache-210829-4

    - name: Install Coverity scan tools
      run: "tools/install_coverity_tools.bat $TOKEN"

    - name: Configure CMake
      run: |
        cov_tools/bin/cov-configure --config $env:OUTDIR/covtest/cov.xml --msvc --template --xml-option=skip_file:".*/libs.*"
        cmake -B $env:OUTDIR -DCMAKE_BUILD_TYPE=Debug -G "Visual Studio 16 2019" -A x64 -DBIT_TYPE=64 .

    - name: Build with Coverity
      run: |
        cov_tools/bin/cov-build --config $env:OUTDIR/covtest/cov.xml --dir $env:OUTDIR/cov-int cmake --build $env:OUTDIR
        cd $env:OUTDIR
        tail cov-int/build-log.txt
        tar -czvf cov-int.tgz cov-int
        cd ..

    - name: Submit tarball to Coverity
      run: curl --form token=$TOKEN --form email=$EMAIL --form file=@${{env.OUTDIR}}/cov-int.tgz --form version="${{github.sha}}" --form description="Automatic submission with GitHub Actions" https://scan.coverity.com/builds?project=pit-ray%2Fwin-vind
      shell: cmd
