name: MinGW-w64 build

on:
  push:
    branches: [ master ]
    tags:
      - v*.*.*
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  x64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Setup Library
      run: "scripts/setup_libs.bat -mingw 64"

    - name: Cache Library
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/libs
        key: x64-libs-cache

    - name: Configure CMake
      run: |
        cmake -B build_mingw_x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "MinGW Makefiles" -DBIT_TYPE=64 -DCCACHE_ENABLE=OFF .

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build_mingw_x64 --config ${{env.BUILD_TYPE}}
