name: MinGW build

on:
  push:
    branches:
      - master
    tags:
      - v*.*.*
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'src/**'
      - '.github/**'
      - 'tests/**'
      - 'tools/**'

  pull_request:
    branches:
      - master
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'src/**'
      - '.github/**'
      - 'tests/**'
      - 'tools/**'


jobs:
  x64:
    runs-on: windows-2019

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2

    - name: Setup Dependencies
      shell: powershell
      run: |
        choco install -y 7zip.install
        curl -OL https://github.com/niXman/mingw-builds-binaries/releases/download/13.2.0-rt_v11-rev0/x86_64-13.2.0-release-win32-seh-ucrt-rt_v11-rev0.7z
        7z x x86_64-13.2.0-release-win32-seh-ucrt-rt_v11-rev0.7z
        echo "CC=${{github.workspace}}/mingw64/bin/gcc.exe" >> $GITHUB_ENV
        echo "CXX=${{github.workspace}}/mingw64/bin/g++.exe" >> $GITHUB_ENV

    - name: Cache Libraries
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/libs/wxWidgets
        key: x64-libs-cache-mingw

    - name: Install Libraries
      run: "tools/install_wxWidgets.bat -mingw 64"

    - name: Configure CMake
      run: |
        cmake -B debug -DCMAKE_BUILD_TYPE=Debug -G "MinGW Makefiles" -DCCACHE_ENABLE=OFF .

    - name: Build
      run: |
        cmake --build debug --config Debug
