name: MinGW build

on:
  push:
    branches:
      - master
#   tags:
#     - v*.*.*
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'

  pull_request:
    branches:
      - master


jobs:
  x64:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v2

    - name: Setup MinGW
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          git
          base-devel
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-cmake

    - name: Cache Libraries
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/libs
        key: x64-libs-cache-210828

    - name: Install Libraries
      run: "tools/setup_libs.bat -mingw 64"

    - name: Configure CMake
      run: |
        cmake -B debug -DCMAKE_BUILD_TYPE=Debug -G "MinGW Makefiles" -DBIT_TYPE=64 -DCCACHE_ENABLE=OFF .

    - name: Build
      run: |
        cmake --build debug --config Debug
