name: build MSVC

on:
  push:
    branches: [ master ]
    tags:
      - v*.*.*
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Debug

jobs:
  Windows-MSVC-64bit:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Library
      run: "scripts/setup_libs.bat -msvc 64"

    - name: Configure CMake
      run: |
        cmake -B ${github.workspace}}/build_64_msvc -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Visual Studio 16 2019" -A x64 -DBIT_TYPE=64 .

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build_64_msvc --config ${{env.BUILD_TYPE}}

  Windows-MSVC-32bit:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Library
      run: "scripts/setup_libs.bat -msvc 32"

    - name: Configure CMake
      run: |
        cmake -B ${github.workspace}}/build_32_msvc -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Visual Studio 16 2019" -A Win32 -DBIT_TYPE=32 .

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build_32_msvc --config ${{env.BUILD_TYPE}}
