name: MSVC build

on:
  push:
    branches: [ master ]
    tags:
      - v*.*.*
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'src/**'
      - '.github/**'
      - 'tests/**'
      - 'tools/**'

  pull_request:
    branches: [ master ]
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'src/**'
      - '.github/**'
      - 'tests/**'
      - 'tools/**'

env:
  BUILD_TYPE: Debug

jobs:
  x64:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build_msvc_x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Visual Studio 16 2019" -A x64 .

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build_msvc_x64 --config ${{env.BUILD_TYPE}}

  x86:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build_msvc_x86 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G "Visual Studio 16 2019" -A Win32 -DBIT_TYPE=32 .

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build_msvc_x86 --config ${{env.BUILD_TYPE}}
