name: release assets

on:
  push:
    tags:
      - v*.*.*

jobs:
  x64-and-x86:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install NSIS
      run: |
        powershell Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
        scoop bucket add extras
        scoop install nsis


    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      env:
        TAG: ${{steps.get_version.outputs.VERSION}}


    - name: Setup x64 MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Cache Libraries
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/libs
        key: x64-libs-cache-210801

    - name: Setup Libraries
      run: "tools/setup_libs.bat -msvc 64"
 
    - name: Create assets
      run: "tools/create_assets.bat ${TAG} -msvc 64"


    - name: Setup x86 MSVC
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Cache Library
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/libs
        key: x86-libs-cache-210801

    - name: Setup Library
      run: "tools/setup_libs.bat -msvc 32"

    - name: Create assets
      run: "tools/create_assets.bat ${TAG} -msvc 32"


    - name: Create release and submit assets
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          bin_64/*64bit.exe.zip
          bin_64/*64bit.zip
          bin_32/*32bit.exe.zip
          bin_32/*32bit.zip
