name: test

on:
  push:
    branches: [ master ]
    tags:
      - v*.*.*
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'src/**'
      - 'tests/**'
      - '.github/**'
      - 'tools/**'

  pull_request:
    branches: [ master ]
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'src/**'
      - '.github/**'
      - 'tests/**'
      - 'tools/**'

env:
  BUILD_TYPE: Debug

jobs:
  test-on-Windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install tools
      run: |
        choco install -y unzip

    - name: Cache Libraries
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/libs
        key: x64-libs-cache-test-220126

    - name: Setup Libraries
      run: "tools/setup_libs.bat -msvc 64"

    - name: Setup Test Framework
      run: "tools/setup_test_framework.bat"

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/tests/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} tests

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/tests/build --config ${{env.BUILD_TYPE}}

    - name: Prepare ICU
      run: |
        cmd /c curl -OL https://github.com/unicode-org/icu/releases/download/release-70-1/icu4c-70_1-Win64-MSVC2019.zip
        unzip icu4c-70_1-Win64-MSVC2019.zip
        cp bin64/icuuc70.dll bin64/icu.dll
        set PATH=${{github.workspace}}/bin64;%PATH%

    - name: Test
      working-directory: ${{github.workspace}}
      run: |
        cd tests/build
        ctest -C ${{env.BUILD_TYPE}} --output-on-failure
        cd ../..
